CodeConstruct/mctp

src/mctp.h
Starting 5.15 kernel has mctp.h as well and provides some of the
defintions, therefore move the ones we need to provide in this header
outside the conditional check so its always provided regardless of
header coming from kernel or not.
Include linux/if_link.h so it can pre-define IFLA_MCTP_UNSPEC and other
defines and there is a check for conditionally providing them here but
kernel does not have such a check, so if linux/if_link.h is included
after this header then we end up with duplicate defines
linux/if_link.h:1267:2: error: redefinition of enumerator 'IFLA_MCTP_UNSPEC'
IFLA_MCTP_UNSPEC,
^
../git/src/mctp.h:74:2: note: previous definition is here
IFLA_MCTP_UNSPEC,
^
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> build: Adjust for kernel mctp.h

src/mctpd.c
Modified the type of NetworkId to uint32 to follow the definition of MCTP/Endpoint.interface in phosphor-dbus-interfaces.
Test log:
- Check the type of NetworkId is 'u'.
root@bmc:~# busctl introspect xyz.openbmc_project.MCTP \
/xyz/openbmc_project/mctp/1/40
NAME                                TYPE      SIGNATURE RESULT/VALUE FLAGS
au.com.CodeConstruct.MCTP.Endpoint  interface -         -            -
.Remove                             method    -         -            -
.SetMTU                             method    u         -            -
org.freedesktop.DBus.Introspectable interface -         -            -
.Introspect                         method    -         s            -
org.freedesktop.DBus.Peer           interface -         -            -
.GetMachineId …
=> Modified the type of NetworkId to uint32_t

src/mctpd.c
Here are a couple of fixes that were identified with slightly broader testing.
I've exercised these on an AST2600 EVB against a Micron 7450 drive. The drive supports `Get Endpoint UUID` but returns the nil UUID, which isn't terribly helpful, but we have the build feature to deal with it. The three recovery paths have been tested with:
1. Setting up the device's endpoint, removing device power, and leaving it unpowered until recovery fails
2. Building with `-Dunsafe-recover-nil-uuid=false`, setting up the device's endpoint, power-cycling the device, and then invoking a recovery. The original endpoint object was removed, and a new endpoint added, observed via `busctl monitor`
3. Building with `-Dunsafe-recover-nil-uuid=true`, setting up the device's endpoint, power-cycling the device, and …
=> Endpoint recovery fixes

README.md, meson.build, src/mctp-netlink.c, src/mctp-ops.c, src/mctp-ops.h, src/mctp.c, src/mctpd.c, tests/conftest.py, tests/mctp-ops-test.c, tests/mctp_test_utils.py, tests/pytest.ini.in, tests/requirements.txt, tests/test-proto.h, tests/test_mctpd.py
This series implements a scriptable test infrastructure for mctpd, mocking both the netlink and AF_MCTP interfaces, to allow arbitrary kernel and external network state.
The majority of the code is a new pytest fixture, which provides small socket interface to an external program (in our case, mctpd), over which the netlink and MCTP communication can be simulated. This allows us to write fairly straightforward tests, including the example in this change:
```python
""" Test the SetupEndpoint dbus call
Using the default system & network ojects, call SetupEndpoint on our mock
endpoint. We expect the dbus call to return the endpoint details, and
the new kernel neighbour and route entries.
"""
async def test_setup_endpoint(dbus, mctpd):
iface = mctpd.system.interfaces[0]
ep = …
```
=> Add mctp test infrastructure

tests/conftest.py, tests/test_mctpd.py
There are several paths of interest through recovery:
1. The device is immediately responsive despite the `Recover` invocation
2. The device fails to respond prior to Treclaim
3. The device is initially unresponsive but recovers before Treclaim
4. The device has been exchanged for another
Add test cases for all four.
=> tests: mctpd endpoint recovery

README.md
calling meson without setup is deprecated and gives a warning
=> add setup param to meson command in README

CHANGELOG.md, src/mctpd.c, tests/test_mctpd.py
get_endpoint_peer() may see an EEXIST while updating the local peer tables; this indicates there was a conflict between a queried EID (via Get Endpoint ID to the peer), and another entry in the peer table.
We currently handle this by returning a dbus error directly from get_endpoint_peer(), but this is recoverable from a SetupEndpoint call, by assigning a new EID.
Instead of returning the dbus error in get_endpoint_peer, leave the EXIST handling to the caller, where the behaviours are different:
- LearnEndpoint needs to propogate the error to the caller
- SetupEndpoint can attempt to assign a new EID
Fixes: https://github.com/CodeConstruct/mctp/issues/19
Reported-by: Muhammad Usama Chaudhry <chaudhryusama@gmail.com>
=> mctpd: handle EEXIST outside of get_endpoint_peer

CHANGELOG.md, docs/mctpd.md, src/mctpd.c, tests/test_mctpd.py
Add a new dbus call to create a new peer with a predefined EID, provided by the caller. This allows other infrastructure to define static EID alocations, have mctpd set up the appropriate routes, neighbours and dbus objects, and have the static EID removed from mctpd's EID pool.
=> mctpd: Add AssignEndpointStatic dbus interface

CHANGELOG.md, meson.build, meson_options.txt
Whether tests should be enabled isn't something that should be auto-detected. Switch the option from `feature` to `boolean`, and cleanup the meson.build file.
The bitbake recipe should be updated to specify the following when bumped:
```
EXTRA_OEMESON = "-Dtests=false"
```
=> Change `test` option to `boolean`

CHANGELOG.md, README.md, conf/mctpd.conf, lib/tomlc99/LICENSE, lib/tomlc99/README, lib/tomlc99/toml.c, lib/tomlc99/toml.h, meson.build, src/mctp-netlink.c, src/mctp-util.h, src/mctp.c, src/mctpd.c
As discussed in #39 and #40, we need a configuration facility for setting things like:
* the overall role (bus owner / endpoint) of mctpd
* mctp implementation parameters (eg., timeout)
* globals (eg., UUID)
This change uses a simple TOML structure, to allow future expansion for per-link settings.
=> Add configuration file facility

CHANGELOG.md, README.md, conf/mctpd-dbus.conf, conf/mctpd.service, docs/endpoint-recovery.md, docs/mctpd.md, meson.build, meson_options.txt, src/mctpd.c, tests/conftest.py, tests/mctp_test_utils.py, tests/test_mctpd.py
This PR implements the dbus rework discussed in #40. From the interface commit:
> Essentially: this uses more standard bus, object and path names, and
> moves away from the xyz.openbmc_project namespace, and use
> au.com.codeconstruct (all lowercase) there instead, as we're not
> specificially an OpenBMC project.
> 
> We also put collections of things (networks and endpoints) under a
> specifically-named object path, so we can introduce new collections
> alongside (interfaces) without compatibility issues
> 
> This means:
> 
>  - the bus owner name is now au.com.codeconstruct.MCTP1
> 
>  - interfaces are namespaced and versioned:
>     - au.com.codeconstruct.MCTP.Endpoint1
>     - au.com.codeconstruct.MCTP.BusOwner1
> 
>  - the top-level entrypoint path is versioned, as
> …
=> dbus rework

CHANGELOG.md, conf/mctpd.conf, docs/mctpd.md, src/mctp-netlink.c, src/mctp-netlink.h, src/mctpd.c
This PR continues the work from https://github.com/CodeConstruct/mctp/pull/39.
I have rebased @ThuBaNguyen 's commit to current `main`, so we have a single commit to implement the dbus change.
=> Add interface objects to dbus

CHANGELOG.md, README.md, docs/endpoint-recovery.md, docs/mctpd.md, src/mctpd.c, tests/mctp_test_utils.py, tests/test_mctpd.py
In https://github.com/CodeConstruct/mctp/commit/9b4eabc3a5e4af5d3f39cd59ddfcc059fe39b961 ("mctpd: use .DRAFT suffix on BusOwner1 interface"), we
renamed BusOwner1 to BusOwner1.DRAFT while it was present on the
top-level dbus object.
Now that we have the interface objects present, we can move the BusOwner
interfaces to their proper location on those interfaces, and drop the
DRAFT1 suffix.
Because we already know the object, we no longer need the interface name
string as the first argument to all calls.
=> dbus `BusOwner` rework

src/mctpd.c
The response from the "Get Message Type Support" request doesn't include the list of message type numbers; it only returns the message type count.
Request:
00 81 05
Response:
00 00 05 00 01
To fix this issue, adjust the response length to include the message type list. The corrected response should be:
00 00 05 00 01 00
=> mctpd: fix incorrect response of Get Message Type Support

docs/endpoint-recovery.md
Apparently I got half-way through a thought before getting distracted. Remove the unfinished description until the thought comes back.
Fixes: #47
Fixes: 7ec2f8daa3a8 ("mctpd: Add support for endpoint recovery")
=> docs: Drop dangling instruction in endpoint recovery

CHANGELOG.md, src/mctp-control-spec.h, src/mctpd.c, tests/conftest.py, tests/test_mctpd.py
This series implements more checking on MCTP control protocol responses: that they have the correct opcode and IID values from the request.
In doing so, we use a common error checking path.
=> Improve checks for MCTP control protocol messages

CHANGELOG.md, src/mctp.c
0x prefix is only added for single-byte addresses, "none" is printed instead of (no-addr).
=> mctp: Improve formatting of interface addresses

CHANGELOG.md, src/mctp-netlink.c, src/mctp-netlink.h, src/mctpd.c, tests/conftest.py
This allows better compatibility with devices that have a low initial allowed packet size and require application negotiation to increase that packet size.
Previously the MTU was left at 0, so matching the currently set MTU of the device.
=> mctpd: Set initial route MTU to interface minimum

meson.build, src/mctp-bench.c
A utility tool that implements a sender and receiver to benchmark mctp throughput. This is split into a sender command and a receive command in the same executable.
The receive command waits for incoming messages, notifies the user of first message received and then prints out measured throughput periodically.
Example usage:
mctp-bench recv
The sender command sends messages continously, the size of which can be set by the user, defaulting to 8 bytes.
Example usage:
mctp-bench send len 1000 eid 8
=> mctp-bench: Add a utility tool to send/receive messages and display throughput

CHANGELOG.md, src/mctp-bench.c, src/mctp-echo.c, src/mctp-netlink.c, src/mctp-req.c
Previously PLDM message type (1) was being used, but it would be better to use a specific type that won't conflict with other uses.
This could still clash with other vendor types, pending future kernel support to distinguish those.
=> Use Vendor message types for mctp-bench, mctp-echo

README.md, src/mctp-netlink.c, src/mctp-netlink.h, src/mctp-ops.c, src/mctp-ops.h, src/mctpd.c, tests/mctp-ops-test.c, tests/mctpd/__init__.py, tests/pytest.ini.in, tests/test_mctpd.py
Previously the duplicate linkmaps would become inconsistent when interfaces were added/removed.
mctpd also attempted to remove a route for a deleted interface, even though the kernel would have already removed that route.
This PR also has a few cleanups encountered while adding a test. 
In the process of adding tests, I realised zero-length lladdr (for eg mctpusb) still adds neighbour entries. Those are not necessary, mctpd now omits adding those.
This should fix #55 and fix #73.
=> Fix mctpd deleted interface handling

src/mctpd.c, tests/conftest.py, tests/mctp_test_utils.py, tests/mctpd/__init__.py, tests/test_mctpd_endpoint.py
This MR adds the capability to write tests for `mctpd` as an endpoint. This caught an uninitialized read bug on link data.
=> Allow passing config as a fixture

meson.build, tests/requirements.txt
This PR is a collection of small QOL changes to the test runner:
1. Make TAP output a tad more useful, with captured logs from `mctpd` subprocess.
2. Allow running without TAP by passing `--interactive` to `meson`.
3. Allow filtering tests (or passing arbitrary flags) to `pytest` via `--test-args`.
As a result, instead of
```
meson test -C obj
cd obj
dbus-run-session env DBUS_STARTER_BUS_TYPE=user pytest
cd ..
```
It can be now
```
meson test -C obj --interactive
```
and for filtering tests:
```
meson test -C obj --interactive --test-args="-k recov"
```
=> QOL changes for test runner

meson.build, src/mctp-client.c
Adds a generic mctp client to use from the cli. Currently does not support extended addressing.
Testing
---
control commands
```
mctp-client type control eid 8 data 0x80 0x02
0x00 0x02 0x00 0x08 0x01 0x00
```
corner case testing
```
mctp-client type control eid 10 data 0x80 0x02
mctp-client: sendto(2): No route to host
mctp-client type control eid 8 data
mctp-client: no data to send
mctp-client type control eid data 0x80 0x02
usage:
mctp-client [net <net>] eid <eid> type <type> data <data>
net defaults to MCTP_NET_ANY, data is space delimited hexadecimal. data must be the last parameter
possible types:
control: control mctp messages per DSP0236
pldm: platform level data model per DSP0241
nc-si: NC-SI traffic over MCTP per DSP0261
ethernet: Ethernet traffic over MCTP per DSP0261
nvme: nvme …
```
=> mctp-client: add a generic mctp client

CHANGELOG.md, src/mctp.c
"none" is printed instead of "(no-addr)" for no-address devices.
This matches the previous change to "mctp addr" in
https://github.com/CodeConstruct/mctp/commit/c519bba4ca238d1c7f83bfc506d6dfa7c9baca98 ("mctp: Improve formatting of interface addresses")
=> mctp: neigh: Only print 0x prefix for 1-byte addrs

CHANGELOG.md, README.md, meson.build, src/mctp-netlink.c, src/mctp-netlink.h, src/mctp-util.c, src/mctp-util.h, src/mctp.c, src/mctpd.c
Now that the gateway support has hit net-next (https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=ad39c12fcee34b8980a80ad5c803bca9906fbd4e), we can add the userspace components that rely on the new rtnetlink interface
=> Add support for gateway & range routing operations

CHANGELOG.md, src/mctp-netlink.c, src/mctp-netlink.h, src/mctpd.c, tests/test_mctpd.py
Interface renames may happen as part of persistent net name rules, so we should handle them in mctpd.
This series checks for name changes in the RTM_GETLINK dumps, and creates `mctp_nl_change` data to represent these. We then add handlers for these events in mctpd, and update the dbus objects to suit.
=> Handle MCTP interface rename events

src/mctp-bench.c
"mctp-bench recv" can now optionally request that a peer start sending with a specified message count and message length.
"mctp-bench recv eid 20 len 987 count 10000"
The send equivalent is not yet implemented. Currently mctp-bench will continue listening forever, since it won't necessarily know that all packets have been received (if drops occur). That could be changed in future.
With default arguments "mctp-bench recv" behaviour is unchanged.
=> mctp-bench: Support recv requests

CHANGELOG.md, conf/mctpd.conf, docs/mctpd.md, src/mctpd.c, tests/test_mctpd.py
This series adds a new section to `mctpd.conf`, allowing bus-owner configuration. We use this to implement the requested dynamic EID ranges control in #94 .
```toml
[bus-owner]
dynamic_eid_range = [50, 60]
```
I'm pulling-in @faizana-nvidia's support for the general `[bus-owner]` section, including the pool-size config, as we will need that in the bridge functionality later anyway.
Fixes: #94
=> mctpd: Add bus-owner configuration, implement dynamic EID setting

src/mctp-control-spec.h, src/mctp-netlink.h
Commit e35f4a5 ("mctpd: avoid bitfield & implicit enum values in wire format") introduced a #include <linux/mctp.h> for mctp_eid_t. However, we want the ability to fall-back to the in-tree definitions, so use the internal mctp.h instead. This will use mctp.h if available.
Fixes: https://github.com/CodeConstruct/mctp/issues/103
Fixes: e35f4a5 ("mctpd: avoid bitfield & implicit enum values in wire format")
=> mctp: don't include linux/mctp.h directly

CHANGELOG.md, docs/mctpd.md, src/mctp-control-spec.h, src/mctpd.c, tests/mctpenv/__init__.py, tests/test_mctpd.py
This PR aims to introduce ALLOCATE_ENDPOINT_ID message support along with MCTP Bridge endpoint into the existing peer structure.
=> Mctp bridge support

src/mctp-bench.c, src/mctp-client.c
Address a couple of warnings on a `x86_64-buildroot-linux-gnu` target.
=> Minor warning fixes

docs/mctpd.md, src/mctpd.c, tests/mctp_test_utils.py, tests/test_mctpd.py
GetMsgType response is hardcoded and always return only control
message support. Add a dbus method RegisterTypeSupport which accept msg
type and versions array as input and reply accordingly in GetMsgType and
GetVersin control commands
Tested by sending GetMsgType and GetVersion from another EP
Default responses for GetMsgType and GetVersion for type 0
5, 0, 1, 0 and 4, 0, 4, 241, 240, 255, 0, 241, 241, 255, 0, 241, 242, 255, 0, 241, 243, 241, 0
After calling
au.com.codeconstruct.MCTP1 /au/com/codeconstruct/mctp1 au.com.codeconstruct.MCTP1 RegisterTypeSupport yau 5 1 0xF1F2F3F4
with a tool which stays alive after method call
Response for GetMsgType and GetVersion for type 5
5, 0, 2, 0, 5 and 4, 0, 1, 244, 243, 242, 241
=> RegisterResponder API
